disabled_rules:
  - colon
  - object_literal
  - file_length
opt_in_rules:
  - empty_count
excluded:
  - Carthage
  - ExampleApp
  - Tests
  - .build
  
line_length: 
  warning: 120
  ignores_comments: true
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
